[NRRPLT-0000] incomplete set of changes to make the scripts work in ubuntu 20.04

diff --git a/nrp_functions b/nrp_functions
--- a/nrp_functions
+++ b/nrp_functions
@@ -182,7 +182,7 @@ function build_gazebo {
   echo Gazebo
   echo -------------------------
   sleep 2
-  if ! echo "$ubuntu_version" | grep 18 >> /dev/null; then
+  if ! echo "$ubuntu_version" | grep 20 >> /dev/null; then
     cmake_args="-DENABLE_TESTS_COMPILATION:BOOL=False"
   fi
   cd "$HBP"/gazebo || { echo ERROR: "$HBP"/gazebo NOT FOUND. You might want to run the clone-all-repos script to get this repo; exit 1; }
@@ -388,7 +388,6 @@ function nrp_build {
       echo -------------------------
       sleep 2
       cd "$HBP"/$i || { echo ERROR: "$HBP"/$i NOT FOUND. You might want to run the clone-all-repos script to get this repo; exit 1; }
-
       mkdir -p build
       cd build
       cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local .. || { echo $i: CMAKE ERROR; print_build_error_message nest-simulator; exit 1; }
@@ -412,77 +411,62 @@ function nrp_build {
     echo -------------------------
     sleep 2
     cd "$HBP"/$i || { echo NOT FOUND. You might want to run the clone-all-repos script to get this repo; exit 1; }
-
     make devinstall || { echo $i BUILD ERROR; exit 1; }
   done
 
-  echo
-  echo -------------------------
-  echo "Fixing Issue with PyNN 0.9.4"
-  echo -------------------------
-  sleep 2
-  # As of 2019-12-21 spynnaker doesn't work with PyNN 0.9.5
-  # There is a bug in PyNN 0.9.4, which is fixed with the following patch.
-  # This Bugfix is needed to run cerebellum.
-  # Remove this Bugfix after upgrading to PyNN 0.9.5
-  sed -i "792s/label=self.id)/label=str(self.id))/" "$NRP_VIRTUAL_ENV"/lib/python2.7/site-packages/pyNN/serialization/sonata.py
-  sed -i "792s/label=self.id)/label=str(self.id))/" "$NRP_VIRTUAL_ENV"/local/lib/python2.7/site-packages/pyNN/serialization/sonata.py
-  rm "$NRP_VIRTUAL_ENV"/lib/python2.7/site-packages/pyNN/serialization/sonata.pyc
-  rm "$NRP_VIRTUAL_ENV"/local/lib/python2.7/site-packages/pyNN/serialization/sonata.pyc
-
   # sPynnaker8 requires enum34, which is problematic in python > 3.4
   # TODO remove as soon as sPyNNaker8 is updated
-  if [[ ($PYTHON_VERSION_MAJOR -ge 3) && ($PYTHON_VERSION_MINOR -ge 4) ]]; then
-     echo
-     echo ---------------------------------------------------------------------
-     echo "Uninstalling enum34 (requirement of sPyNNaker8) from NRP_VIRTUAL_ENV"
-     echo ---------------------------------------------------------------------
-     source ${NRP_VIRTUAL_ENV}/bin/activate
-     $PIP_CMD uninstall -y enum34
-     deactivate
-  fi
+  # if [[ ($PYTHON_VERSION_MAJOR -ge 3) && ($PYTHON_VERSION_MINOR -ge 4) ]]; then
+  #    echo
+  #    echo ---------------------------------------------------------------------
+  #    echo "Uninstalling enum34 (requirement of sPyNNaker8) from NRP_VIRTUAL_ENV"
+  #    echo ---------------------------------------------------------------------
+  #    source ${NRP_VIRTUAL_ENV}/bin/activate
+  #    $PIP_CMD uninstall -y enum34
+  #    deactivate
+  # fi
 
-  echo
-  echo -------------------------
-  echo "Fixing Issue with PyNN 0.9.4"
-  echo -------------------------
-  sleep 2
+  # echo
+  # echo -------------------------
+  # echo "Fixing Issue with PyNN 0.9.4"
+  # echo -------------------------
+  # sleep 2
   # As of 2019-12-21 spynnaker doesn't work with PyNN 0.9.5
   # There is a bug in PyNN 0.9.4, which is fixed with the following patch.
   # This Bugfix is needed to run cerebellum.
   # Remove this Bugfix after upgrading to PyNN 0.9.5
-  VENV_LOCAL_LIB=$NRP_VIRTUAL_ENV/local/lib/python$PYTHON_VERSION_MAJOR_MINOR
-  VENV_LIB=$NRP_VIRTUAL_ENV/lib/python$PYTHON_VERSION_MAJOR_MINOR
-  sed -i "792s/label=self.id)/label=str(self.id))/" {"$VENV_LIB","$VENV_LOCAL_LIB"}/site-packages/pyNN/serialization/sonata.py
-  rm {"$VENV_LIB","$VENV_LOCAL_LIB"}/site-packages/pyNN/serialization/sonata.pyc
+  # VENV_LOCAL_LIB=$NRP_VIRTUAL_ENV/local/lib/python$PYTHON_VERSION_MAJOR_MINOR
+  # VENV_LIB=$NRP_VIRTUAL_ENV/lib/python$PYTHON_VERSION_MAJOR_MINOR
+  # sed -i "792s/label=self.id)/label=str(self.id))/" {"$VENV_LIB","$VENV_LOCAL_LIB"}/site-packages/pyNN/serialization/sonata.py
+  # rm {"$VENV_LIB","$VENV_LOCAL_LIB"}/site-packages/pyNN/serialization/sonata.pyc
 
   # Only perform this step for Ubuntu16
-  if ! echo "$ubuntu_version" | grep 18 >> /dev/null; then
-    ubuntu_fix_cv2
-  fi
+  # if ! echo "$ubuntu_version" | grep 18 >> /dev/null; then
+  #   ubuntu_fix_cv2
+  # fi
 
-  for i in brainvisualizer ExDFrontend nrpBackendProxy SlurmClusterMonitor
-  do
-    echo
-    echo -----------------------
-    echo $i
-    echo -----------------------
-    sleep 2
-    cd "$HBP"/$i || { echo NOT FOUND. You might want to run the clone-all-repos script to get this repo; exit 1; }
+  # for i in brainvisualizer ExDFrontend nrpBackendProxy SlurmClusterMonitor
+  # do
+  #   echo
+  #   echo -----------------------
+  #   echo $i
+  #   echo -----------------------
+  #   sleep 2
+  #   cd "$HBP"/$i || { echo ERROR; exit 1; }
 
-    # Dedupe helps prevents known issue "npm ERR! enoent ENOENT: no such file or directory, rename"
-    # For more information see: https://github.com/zurb/foundation-sites/issues/10826
-    npm dedupe || { echo  $i INSTALL ERROR; exit 1; }
-    rm package-lock.json
-    git checkout -- package.json
-    VENV_CMD=$VIRTUALENV_CMD
-    export VENV_CMD  # used by nrpBackendProxy's install
-    npm install --no-save || { echo  $i INSTALL ERROR; exit 1; }
-    if [ "$i" == "ExDFrontend" ]; then
-        grunt build || { echo GRUNT BUILD FAILED; exit 1; }
-    fi
-    unset VENV_CMD
-  done
+  #   # Dedupe helps prevents known issue "npm ERR! enoent ENOENT: no such file or directory, rename"
+  #   # For more information see: https://github.com/zurb/foundation-sites/issues/10826
+  #   npm dedupe || { echo  $i INSTALL ERROR; exit 1; }
+  #   rm package-lock.json
+  #   git checkout -- package.json
+  #   VENV_CMD=$VIRTUALENV_CMD
+  #   export VENV_CMD  # used by nrpBackendProxy's install
+  #   npm install --no-save || { echo  $i INSTALL ERROR; exit 1; }
+  #   if [ "$i" == "ExDFrontend" ]; then
+  #       grunt build || { echo GRUNT BUILD FAILED; exit 1; }
+  #   fi
+  #   unset VENV_CMD
+  # done
 
   build_gzweb
   build_frontend_state_machine_editor
@@ -656,7 +640,7 @@ function add_new_user_tingoDB {
     echo "Are you finished with your input? (Answering no will abort)"
     read -p "[Y/n] " -n 1 -r REPLY || { echo ERROR; exit 1; }
     echo
-    if [[( $REPLY =~ ^[Nn] ) ]]; then
+    if [[ ( $REPLY =~ ^[Nn] ) ]]; then
       exit 0
     fi
   fi
