[NRRPLT-5545] Update_nrp prompts the user to stash his unstaged changes
- The update_nrp script now checks if there are local changes in a repo,
and if there are, it prompts the user to stash them. Upon user confirmation it
 stashes, else it stops the execution with an error (as there is no point in updating without checking the correct branch)

Change-Id: If7a8cf06c7d9ef2a5602df3ac11b39a0f308d9a2

diff --git a/nrp_functions b/nrp_functions
--- a/nrp_functions
+++ b/nrp_functions
@@ -82,6 +82,24 @@ function nrp_rebase {
     echo -------------------------
     sleep 2
     cd $i || { echo ERROR;exit 1; }
+    
+    # in case there are unstaged changes we prompt the user to stash them
+    if ! git diff-files --quiet --ignore-submodules --
+    then
+      echo >&2 "About to checkout the $branch branch, you have the following unstaged changes:"
+      git diff-files --name-status -r --ignore-submodules -- >&2
+      echo "Would you like to stash your changes [y] or you would like to abort?"
+      read -p "[Y/n] " -n 1 -r REPLY || { echo ERROR;exit 1; }
+      if [[ ( -z "$REPLY" ) || ( $REPLY =~ ^[Yy] ) ]]; then
+        echo
+        git stash || { echo ERROR;exit 1; }
+      else
+        echo
+        echo "Could not continue script execution since you have unstaged changes."
+        echo ERROR;exit 1;
+      fi
+    fi
+    
     git checkout $branch && git pull --rebase || { echo ERROR;exit 1; }
     cd ..
   done
