Merged in hotfixUserWarning (pull request #44)
[NRRPLT-7465] Update the user scripts to warn users to remove their build folder if the build fails

* [NRRPLT-7465] Update the user scripts to warn users to remove their build folder if the build fails

* [NRRPLT-7465] Add cmake check

* [NRRPLT-7465] Yet more checks

* [NRRPLT-7465] Add check for cerebellum cmake as well

Approved-by: Manos Angelidis <angelidis@fortiss.org>
Approved-by: Axel von Arnim <axel.vonarnim@fortiss.org>

diff --git a/nrp_functions b/nrp_functions
--- a/nrp_functions
+++ b/nrp_functions
@@ -19,6 +19,13 @@ printf "| the NRP.                                                              
 printf "+--------------------------------------------------------------------------------------+\033[0m\n"
 fi
 
+function print_build_error_message {
+printf "\033[1;31m+-------------------------- $1 build FAILED -------------------------------------+\n"
+printf "| The build process failed, try removing the $1/build folder and relaunch this   |\n"
+printf "| script                                                                              |\n"
+printf "+-------------------------------------------------------------------------------------+\033[0m\n"
+}
+
 function checkssh {
     echo "Checking $1"
     touch "$touchfilebase""$1"
@@ -81,8 +88,8 @@ function build_nest {
     if [[ $option == "spiking-cerebellum" ]]; then
       cmake_args="${cmake_args} -Dwith-music=ON"
     fi
-    cmake $cmake_args .. || { echo NEST: CMAKE ERROR; exit 1; }
-    make -j$NRP_NUM_MAKE_PROCESSES || { echo NEST: BUILD ERROR; exit 1; }
+    cmake $cmake_args .. || { echo CMAKE ERROR; print_build_error_message nest-simulator; exit 1; }
+    make -j$NRP_NUM_MAKE_PROCESSES || { echo nest-simulator; print_build_error_message nest-simulator; exit 1; }
     make install || { echo NEST: INSTALL ERROR; exit 1; }
 
     # Optional: install UGR's Cerebellum model plugin
@@ -95,10 +102,11 @@ function build_nest {
       echo
       cd $HBP/nest-simulator/SpikingCerebellum/src/CerebellumModule
       mkdir -p build && cd build && cmake .. && make && make install
-      cd ../../../../build/ && cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/.local \
+      cd ../../../../build/ || { echo ERROR; exit 1; }
+      cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/.local \
           -Dwith-gsl=ON -Dwith-mpi=ON -Dwith-music=ON -Dexternal-modules=cerebellum \
-          ..
-      make -j$NRP_NUM_MAKE_PROCESSES || { echo NEST-SPIKING-CEREBELLUM: BUILD ERROR; exit 1; }
+          .. || { echo CMAKE spiking-cerebellum; print_build_error_message nest-simulator; exit 1; }
+      make -j$NRP_NUM_MAKE_PROCESSES || { echo spiking-cerebellum; print_build_error_message nest-simulator; exit 1; }
       make install || { echo NEST-SPIKING-CEREBELLUM: INSTALL ERROR; exit 1; }
     fi
 
@@ -128,7 +136,7 @@ function build_music {
   ./autogen.sh || { echo ERROR; exit 1; }
   autoreconf --force --install
   ./configure --prefix=$HOME/.local MPI_CXX=mpicxx || { echo ERROR; exit 1; }
-  make -j$NRP_NUM_MAKE_PROCESSES || { echo MUSIC BUILD ERROR; exit 1; }
+  make -j$NRP_NUM_MAKE_PROCESSES || { echo music; print_build_error_message MUSIC; exit 1; }
   make install || { echo MUSIC INSTALL ERROR; exit 1; }
   rm -rf build_venv || { echo ERROR; exit 1; }
   rm mpich2version || { echo ERROR; exit 1; }
@@ -173,7 +181,7 @@ function build_mpich {
   fi
   cd mpich-3.1.4 || { echo ERROR accessing mpich-3.1.4 directory; exit 1; }
   ./configure --enable-fast=all,O3 --prefix=$HOME/.local || { echo ERROR configuring mpich build; exit 1; }
-  make -j$NRP_NUM_MAKE_PROCESSES || { echo MPICH BUILD ERROR; exit 1; }
+  make -j$NRP_NUM_MAKE_PROCESSES || { echo mpich; print_build_error_message mpich; exit 1; }
   make install || { echo ERROR installing mpich in $HOME/.local; exit 1; }
 }
 
@@ -186,8 +194,8 @@ function build_gazebo {
   cd $HBP/gazebo || { echo ERROR: $HBP/gazebo NOT FOUND; exit 1; }
   mkdir -p build
   cd build
-  cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local .. || { echo ERROR; exit 1; }
-  make -j$NRP_NUM_MAKE_PROCESSES || { echo GAZEBO BUILD ERROR; exit 1; }
+  cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local .. || { echo gazebo; print_build_error_message gazebo; exit 1; }
+  make -j$NRP_NUM_MAKE_PROCESSES || { echo gazebo; print_build_error_message gazebo; exit 1; }
   make install || { echo GAZEBO INSTALL ERROR; exit 1; }
 }
 
@@ -374,8 +382,8 @@ function nrp_build {
       cd $HBP/$i || { echo ERROR: $HBP/$i NOT FOUND ; exit 1; }
       mkdir -p build
       cd build
-      cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local .. || { echo $i: CMAKE ERROR; exit 1; }
-      make -j$NRP_NUM_MAKE_PROCESSES || { echo $i: BUILD ERROR; exit 1; }
+      cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local .. || { echo $i: CMAKE ERROR; print_build_error_message nest-simulator; exit 1; }
+      make -j$NRP_NUM_MAKE_PROCESSES || { echo $i; print_build_error_message $i; exit 1; }
       make install || { echo $i: INSTALL ERROR; exit 1; }
     done
 
